// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msp/identities.proto

package org.hyperledger.fabric.protos.msp;

public final class Identities {
  private Identities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SerializedIdentityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msp.SerializedIdentity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The identifier of the associated membership service provider
     * </pre>
     *
     * <code>string mspid = 1;</code>
     */
    java.lang.String getMspid();
    /**
     * <pre>
     * The identifier of the associated membership service provider
     * </pre>
     *
     * <code>string mspid = 1;</code>
     */
    com.google.protobuf.ByteString
        getMspidBytes();

    /**
     * <pre>
     * the Identity, serialized according to the rules of its MPS
     * </pre>
     *
     * <code>bytes id_bytes = 2;</code>
     */
    com.google.protobuf.ByteString getIdBytes();
  }
  /**
   * <pre>
   * This struct represents an Identity
   * (with its MSP identifier) to be used
   * to serialize it and deserialize it
   * </pre>
   *
   * Protobuf type {@code msp.SerializedIdentity}
   */
  public  static final class SerializedIdentity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msp.SerializedIdentity)
      SerializedIdentityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SerializedIdentity.newBuilder() to construct.
    private SerializedIdentity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerializedIdentity() {
      mspid_ = "";
      idBytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SerializedIdentity();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SerializedIdentity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mspid_ = s;
              break;
            }
            case 18: {

              idBytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdentity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdentity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity.class, org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity.Builder.class);
    }

    public static final int MSPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object mspid_;
    /**
     * <pre>
     * The identifier of the associated membership service provider
     * </pre>
     *
     * <code>string mspid = 1;</code>
     */
    public java.lang.String getMspid() {
      java.lang.Object ref = mspid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mspid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The identifier of the associated membership service provider
     * </pre>
     *
     * <code>string mspid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMspidBytes() {
      java.lang.Object ref = mspid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mspid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString idBytes_;
    /**
     * <pre>
     * the Identity, serialized according to the rules of its MPS
     * </pre>
     *
     * <code>bytes id_bytes = 2;</code>
     */
    public com.google.protobuf.ByteString getIdBytes() {
      return idBytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMspidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mspid_);
      }
      if (!idBytes_.isEmpty()) {
        output.writeBytes(2, idBytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMspidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mspid_);
      }
      if (!idBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, idBytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity)) {
        return super.equals(obj);
      }
      org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity other = (org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity) obj;

      if (!getMspid()
          .equals(other.getMspid())) return false;
      if (!getIdBytes()
          .equals(other.getIdBytes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSPID_FIELD_NUMBER;
      hash = (53 * hash) + getMspid().hashCode();
      hash = (37 * hash) + ID_BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getIdBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This struct represents an Identity
     * (with its MSP identifier) to be used
     * to serialize it and deserialize it
     * </pre>
     *
     * Protobuf type {@code msp.SerializedIdentity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msp.SerializedIdentity)
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdentityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdentity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdentity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity.class, org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity.Builder.class);
      }

      // Construct using org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mspid_ = "";

        idBytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdentity_descriptor;
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity getDefaultInstanceForType() {
        return org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity.getDefaultInstance();
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity build() {
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity buildPartial() {
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity result = new org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity(this);
        result.mspid_ = mspid_;
        result.idBytes_ = idBytes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity) {
          return mergeFrom((org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity other) {
        if (other == org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity.getDefaultInstance()) return this;
        if (!other.getMspid().isEmpty()) {
          mspid_ = other.mspid_;
          onChanged();
        }
        if (other.getIdBytes() != com.google.protobuf.ByteString.EMPTY) {
          setIdBytes(other.getIdBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mspid_ = "";
      /**
       * <pre>
       * The identifier of the associated membership service provider
       * </pre>
       *
       * <code>string mspid = 1;</code>
       */
      public java.lang.String getMspid() {
        java.lang.Object ref = mspid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mspid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The identifier of the associated membership service provider
       * </pre>
       *
       * <code>string mspid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMspidBytes() {
        java.lang.Object ref = mspid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mspid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The identifier of the associated membership service provider
       * </pre>
       *
       * <code>string mspid = 1;</code>
       */
      public Builder setMspid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mspid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The identifier of the associated membership service provider
       * </pre>
       *
       * <code>string mspid = 1;</code>
       */
      public Builder clearMspid() {
        
        mspid_ = getDefaultInstance().getMspid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The identifier of the associated membership service provider
       * </pre>
       *
       * <code>string mspid = 1;</code>
       */
      public Builder setMspidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mspid_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString idBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * the Identity, serialized according to the rules of its MPS
       * </pre>
       *
       * <code>bytes id_bytes = 2;</code>
       */
      public com.google.protobuf.ByteString getIdBytes() {
        return idBytes_;
      }
      /**
       * <pre>
       * the Identity, serialized according to the rules of its MPS
       * </pre>
       *
       * <code>bytes id_bytes = 2;</code>
       */
      public Builder setIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the Identity, serialized according to the rules of its MPS
       * </pre>
       *
       * <code>bytes id_bytes = 2;</code>
       */
      public Builder clearIdBytes() {
        
        idBytes_ = getDefaultInstance().getIdBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msp.SerializedIdentity)
    }

    // @@protoc_insertion_point(class_scope:msp.SerializedIdentity)
    private static final org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity();
    }

    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerializedIdentity>
        PARSER = new com.google.protobuf.AbstractParser<SerializedIdentity>() {
      @java.lang.Override
      public SerializedIdentity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SerializedIdentity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerializedIdentity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerializedIdentity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.hyperledger.fabric.protos.msp.Identities.SerializedIdentity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SerializedIdemixIdentityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msp.SerializedIdemixIdentity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * nym_x is the X-component of the pseudonym elliptic curve point.
     * It is a []byte representation of an amcl.BIG
     * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
     * </pre>
     *
     * <code>bytes nym_x = 1;</code>
     */
    com.google.protobuf.ByteString getNymX();

    /**
     * <pre>
     * nym_y is the Y-component of the pseudonym elliptic curve point.
     * It is a []byte representation of an amcl.BIG
     * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
     * </pre>
     *
     * <code>bytes nym_y = 2;</code>
     */
    com.google.protobuf.ByteString getNymY();

    /**
     * <pre>
     * ou contains the organizational unit of the idemix identity
     * </pre>
     *
     * <code>bytes ou = 3;</code>
     */
    com.google.protobuf.ByteString getOu();

    /**
     * <pre>
     * role contains the role of this identity (e.g., ADMIN or MEMBER)
     * </pre>
     *
     * <code>bytes role = 4;</code>
     */
    com.google.protobuf.ByteString getRole();

    /**
     * <pre>
     * proof contains the cryptographic evidence that this identity is valid
     * </pre>
     *
     * <code>bytes proof = 5;</code>
     */
    com.google.protobuf.ByteString getProof();
  }
  /**
   * <pre>
   * This struct represents an Idemix Identity
   * to be used to serialize it and deserialize it.
   * The IdemixMSP will first serialize an idemix identity to bytes using
   * this proto, and then uses these bytes as id_bytes in SerializedIdentity
   * </pre>
   *
   * Protobuf type {@code msp.SerializedIdemixIdentity}
   */
  public  static final class SerializedIdemixIdentity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msp.SerializedIdemixIdentity)
      SerializedIdemixIdentityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SerializedIdemixIdentity.newBuilder() to construct.
    private SerializedIdemixIdentity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerializedIdemixIdentity() {
      nymX_ = com.google.protobuf.ByteString.EMPTY;
      nymY_ = com.google.protobuf.ByteString.EMPTY;
      ou_ = com.google.protobuf.ByteString.EMPTY;
      role_ = com.google.protobuf.ByteString.EMPTY;
      proof_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SerializedIdemixIdentity();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SerializedIdemixIdentity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              nymX_ = input.readBytes();
              break;
            }
            case 18: {

              nymY_ = input.readBytes();
              break;
            }
            case 26: {

              ou_ = input.readBytes();
              break;
            }
            case 34: {

              role_ = input.readBytes();
              break;
            }
            case 42: {

              proof_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdemixIdentity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdemixIdentity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity.class, org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity.Builder.class);
    }

    public static final int NYM_X_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString nymX_;
    /**
     * <pre>
     * nym_x is the X-component of the pseudonym elliptic curve point.
     * It is a []byte representation of an amcl.BIG
     * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
     * </pre>
     *
     * <code>bytes nym_x = 1;</code>
     */
    public com.google.protobuf.ByteString getNymX() {
      return nymX_;
    }

    public static final int NYM_Y_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString nymY_;
    /**
     * <pre>
     * nym_y is the Y-component of the pseudonym elliptic curve point.
     * It is a []byte representation of an amcl.BIG
     * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
     * </pre>
     *
     * <code>bytes nym_y = 2;</code>
     */
    public com.google.protobuf.ByteString getNymY() {
      return nymY_;
    }

    public static final int OU_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString ou_;
    /**
     * <pre>
     * ou contains the organizational unit of the idemix identity
     * </pre>
     *
     * <code>bytes ou = 3;</code>
     */
    public com.google.protobuf.ByteString getOu() {
      return ou_;
    }

    public static final int ROLE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString role_;
    /**
     * <pre>
     * role contains the role of this identity (e.g., ADMIN or MEMBER)
     * </pre>
     *
     * <code>bytes role = 4;</code>
     */
    public com.google.protobuf.ByteString getRole() {
      return role_;
    }

    public static final int PROOF_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString proof_;
    /**
     * <pre>
     * proof contains the cryptographic evidence that this identity is valid
     * </pre>
     *
     * <code>bytes proof = 5;</code>
     */
    public com.google.protobuf.ByteString getProof() {
      return proof_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!nymX_.isEmpty()) {
        output.writeBytes(1, nymX_);
      }
      if (!nymY_.isEmpty()) {
        output.writeBytes(2, nymY_);
      }
      if (!ou_.isEmpty()) {
        output.writeBytes(3, ou_);
      }
      if (!role_.isEmpty()) {
        output.writeBytes(4, role_);
      }
      if (!proof_.isEmpty()) {
        output.writeBytes(5, proof_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!nymX_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, nymX_);
      }
      if (!nymY_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, nymY_);
      }
      if (!ou_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, ou_);
      }
      if (!role_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, role_);
      }
      if (!proof_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, proof_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity)) {
        return super.equals(obj);
      }
      org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity other = (org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity) obj;

      if (!getNymX()
          .equals(other.getNymX())) return false;
      if (!getNymY()
          .equals(other.getNymY())) return false;
      if (!getOu()
          .equals(other.getOu())) return false;
      if (!getRole()
          .equals(other.getRole())) return false;
      if (!getProof()
          .equals(other.getProof())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NYM_X_FIELD_NUMBER;
      hash = (53 * hash) + getNymX().hashCode();
      hash = (37 * hash) + NYM_Y_FIELD_NUMBER;
      hash = (53 * hash) + getNymY().hashCode();
      hash = (37 * hash) + OU_FIELD_NUMBER;
      hash = (53 * hash) + getOu().hashCode();
      hash = (37 * hash) + ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getRole().hashCode();
      hash = (37 * hash) + PROOF_FIELD_NUMBER;
      hash = (53 * hash) + getProof().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This struct represents an Idemix Identity
     * to be used to serialize it and deserialize it.
     * The IdemixMSP will first serialize an idemix identity to bytes using
     * this proto, and then uses these bytes as id_bytes in SerializedIdentity
     * </pre>
     *
     * Protobuf type {@code msp.SerializedIdemixIdentity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msp.SerializedIdemixIdentity)
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdemixIdentity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdemixIdentity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity.class, org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity.Builder.class);
      }

      // Construct using org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nymX_ = com.google.protobuf.ByteString.EMPTY;

        nymY_ = com.google.protobuf.ByteString.EMPTY;

        ou_ = com.google.protobuf.ByteString.EMPTY;

        role_ = com.google.protobuf.ByteString.EMPTY;

        proof_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.fabric.protos.msp.Identities.internal_static_msp_SerializedIdemixIdentity_descriptor;
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity getDefaultInstanceForType() {
        return org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity.getDefaultInstance();
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity build() {
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity buildPartial() {
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity result = new org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity(this);
        result.nymX_ = nymX_;
        result.nymY_ = nymY_;
        result.ou_ = ou_;
        result.role_ = role_;
        result.proof_ = proof_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity) {
          return mergeFrom((org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity other) {
        if (other == org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity.getDefaultInstance()) return this;
        if (other.getNymX() != com.google.protobuf.ByteString.EMPTY) {
          setNymX(other.getNymX());
        }
        if (other.getNymY() != com.google.protobuf.ByteString.EMPTY) {
          setNymY(other.getNymY());
        }
        if (other.getOu() != com.google.protobuf.ByteString.EMPTY) {
          setOu(other.getOu());
        }
        if (other.getRole() != com.google.protobuf.ByteString.EMPTY) {
          setRole(other.getRole());
        }
        if (other.getProof() != com.google.protobuf.ByteString.EMPTY) {
          setProof(other.getProof());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString nymX_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * nym_x is the X-component of the pseudonym elliptic curve point.
       * It is a []byte representation of an amcl.BIG
       * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
       * </pre>
       *
       * <code>bytes nym_x = 1;</code>
       */
      public com.google.protobuf.ByteString getNymX() {
        return nymX_;
      }
      /**
       * <pre>
       * nym_x is the X-component of the pseudonym elliptic curve point.
       * It is a []byte representation of an amcl.BIG
       * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
       * </pre>
       *
       * <code>bytes nym_x = 1;</code>
       */
      public Builder setNymX(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nymX_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * nym_x is the X-component of the pseudonym elliptic curve point.
       * It is a []byte representation of an amcl.BIG
       * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
       * </pre>
       *
       * <code>bytes nym_x = 1;</code>
       */
      public Builder clearNymX() {
        
        nymX_ = getDefaultInstance().getNymX();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nymY_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * nym_y is the Y-component of the pseudonym elliptic curve point.
       * It is a []byte representation of an amcl.BIG
       * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
       * </pre>
       *
       * <code>bytes nym_y = 2;</code>
       */
      public com.google.protobuf.ByteString getNymY() {
        return nymY_;
      }
      /**
       * <pre>
       * nym_y is the Y-component of the pseudonym elliptic curve point.
       * It is a []byte representation of an amcl.BIG
       * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
       * </pre>
       *
       * <code>bytes nym_y = 2;</code>
       */
      public Builder setNymY(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nymY_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * nym_y is the Y-component of the pseudonym elliptic curve point.
       * It is a []byte representation of an amcl.BIG
       * The pseudonym can be seen as a public key of the identity, it is used to verify signatures.
       * </pre>
       *
       * <code>bytes nym_y = 2;</code>
       */
      public Builder clearNymY() {
        
        nymY_ = getDefaultInstance().getNymY();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString ou_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * ou contains the organizational unit of the idemix identity
       * </pre>
       *
       * <code>bytes ou = 3;</code>
       */
      public com.google.protobuf.ByteString getOu() {
        return ou_;
      }
      /**
       * <pre>
       * ou contains the organizational unit of the idemix identity
       * </pre>
       *
       * <code>bytes ou = 3;</code>
       */
      public Builder setOu(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ou_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ou contains the organizational unit of the idemix identity
       * </pre>
       *
       * <code>bytes ou = 3;</code>
       */
      public Builder clearOu() {
        
        ou_ = getDefaultInstance().getOu();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString role_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * role contains the role of this identity (e.g., ADMIN or MEMBER)
       * </pre>
       *
       * <code>bytes role = 4;</code>
       */
      public com.google.protobuf.ByteString getRole() {
        return role_;
      }
      /**
       * <pre>
       * role contains the role of this identity (e.g., ADMIN or MEMBER)
       * </pre>
       *
       * <code>bytes role = 4;</code>
       */
      public Builder setRole(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        role_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * role contains the role of this identity (e.g., ADMIN or MEMBER)
       * </pre>
       *
       * <code>bytes role = 4;</code>
       */
      public Builder clearRole() {
        
        role_ = getDefaultInstance().getRole();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString proof_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * proof contains the cryptographic evidence that this identity is valid
       * </pre>
       *
       * <code>bytes proof = 5;</code>
       */
      public com.google.protobuf.ByteString getProof() {
        return proof_;
      }
      /**
       * <pre>
       * proof contains the cryptographic evidence that this identity is valid
       * </pre>
       *
       * <code>bytes proof = 5;</code>
       */
      public Builder setProof(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proof_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * proof contains the cryptographic evidence that this identity is valid
       * </pre>
       *
       * <code>bytes proof = 5;</code>
       */
      public Builder clearProof() {
        
        proof_ = getDefaultInstance().getProof();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msp.SerializedIdemixIdentity)
    }

    // @@protoc_insertion_point(class_scope:msp.SerializedIdemixIdentity)
    private static final org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity();
    }

    public static org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerializedIdemixIdentity>
        PARSER = new com.google.protobuf.AbstractParser<SerializedIdemixIdentity>() {
      @java.lang.Override
      public SerializedIdemixIdentity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SerializedIdemixIdentity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerializedIdemixIdentity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerializedIdemixIdentity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.hyperledger.fabric.protos.msp.Identities.SerializedIdemixIdentity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_SerializedIdentity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msp_SerializedIdentity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msp_SerializedIdemixIdentity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msp_SerializedIdemixIdentity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024msp/identities.proto\022\003msp\"5\n\022Serialize" +
      "dIdentity\022\r\n\005mspid\030\001 \001(\t\022\020\n\010id_bytes\030\002 \001" +
      "(\014\"a\n\030SerializedIdemixIdentity\022\r\n\005nym_x\030" +
      "\001 \001(\014\022\r\n\005nym_y\030\002 \001(\014\022\n\n\002ou\030\003 \001(\014\022\014\n\004role" +
      "\030\004 \001(\014\022\r\n\005proof\030\005 \001(\014BP\n!org.hyperledger" +
      ".fabric.protos.mspZ+github.com/hyperledg" +
      "er/fabric-protos-go/mspb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_msp_SerializedIdentity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msp_SerializedIdentity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msp_SerializedIdentity_descriptor,
        new java.lang.String[] { "Mspid", "IdBytes", });
    internal_static_msp_SerializedIdemixIdentity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msp_SerializedIdemixIdentity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msp_SerializedIdemixIdentity_descriptor,
        new java.lang.String[] { "NymX", "NymY", "Ou", "Role", "Proof", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
