/*
 * Copyright IBM Corp. 2018 All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

plugins {
    alias(libs.plugins.versions)
    alias(libs.plugins.spotless)
    alias(libs.plugins.nmcp.aggregation)
    alias(libs.plugins.nmcp) apply false
}

version = '2.5.11'

// If the nightly property is set, then this is the scheduled main
// build - and we should publish this to artifactory
//
// Use the .dev.<number> format to match Maven convention
if (properties.containsKey('NIGHTLY')) {
    version = version + '.dev.' + getDate()
    ext.nightly = true   // set property for use in subprojects
} else {
    ext.nightly = false
}

nmcpAggregation {
    centralPortal {
        username = findProperty('mavenCentralUsername')
        password = findProperty('mavenCentralPassword')
        publishingType = "AUTOMATIC"
    }
}

dependencies {
    nmcpAggregation(project(':fabric-chaincode-shim'))
}

allprojects {
    apply(plugin: libs.plugins.spotless.get().pluginId)
    apply(plugin: libs.plugins.versions.get().pluginId)

    repositories {
        mavenCentral()
    }

    spotless {
        format 'misc', {
            target '*.gradle', '.gitattributes', '.gitignore'
            trimTrailingWhitespace()
            leadingTabsToSpaces()
            endWithNewline()
        }
    }

    tasks.named("dependencyUpdates").configure {
        checkConstraints = true
        gradleReleaseChannel = 'current'
        revision = 'release'
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: "maven-publish"

    group = 'org.hyperledger.fabric-chaincode-java'
    version = rootProject.version

    compileJava {
        options.release = 11
        options.compilerArgs += ['-Werror', '-Xlint:all']
    }

    dependencies {
        implementation(libs.commons.cli)
        implementation(libs.commons.logging)

        testImplementation platform(libs.junit.bom)
        testImplementation(libs.junit.jupiter)
        testRuntimeOnly(libs.junit.platform.launcher)
        testImplementation(libs.assertj)
        testImplementation(libs.mockito.core)
        testImplementation(libs.system.stubs.jupiter)

        testImplementation(libs.hamcrest)
    }

    test {
        useJUnitPlatform()
    }

    spotless {
        java {
            forbidWildcardImports()
            formatAnnotations()
            palantirJavaFormat().formatJavadoc(true)
            removeUnusedImports()
            shortenFullyQualifiedTypes()
        }
    }
}

// Get the date in the reverse format for sorting
static def getDate() {
    def date = new Date()
    def formattedDate = date.format('yyyyMMdd')
    return formattedDate
}
