// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer/chaincode_event.proto

package org.hyperledger.fabric.protos.peer;

public final class ChaincodeEventPackage {
  private ChaincodeEventPackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChaincodeEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.ChaincodeEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string chaincode_id = 1;</code>
     */
    java.lang.String getChaincodeId();
    /**
     * <code>string chaincode_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getChaincodeIdBytes();

    /**
     * <code>string tx_id = 2;</code>
     */
    java.lang.String getTxId();
    /**
     * <code>string tx_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getTxIdBytes();

    /**
     * <code>string event_name = 3;</code>
     */
    java.lang.String getEventName();
    /**
     * <code>string event_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getEventNameBytes();

    /**
     * <code>bytes payload = 4;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   *ChaincodeEvent is used for events and registrations that are specific to chaincode
   *string type - "chaincode"
   * </pre>
   *
   * Protobuf type {@code protos.ChaincodeEvent}
   */
  public  static final class ChaincodeEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.ChaincodeEvent)
      ChaincodeEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChaincodeEvent.newBuilder() to construct.
    private ChaincodeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChaincodeEvent() {
      chaincodeId_ = "";
      txId_ = "";
      eventName_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChaincodeEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChaincodeEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              chaincodeId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              txId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              eventName_ = s;
              break;
            }
            case 34: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.internal_static_protos_ChaincodeEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.internal_static_protos_ChaincodeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent.class, org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent.Builder.class);
    }

    public static final int CHAINCODE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object chaincodeId_;
    /**
     * <code>string chaincode_id = 1;</code>
     */
    public java.lang.String getChaincodeId() {
      java.lang.Object ref = chaincodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chaincodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string chaincode_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChaincodeIdBytes() {
      java.lang.Object ref = chaincodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chaincodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TX_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object txId_;
    /**
     * <code>string tx_id = 2;</code>
     */
    public java.lang.String getTxId() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txId_ = s;
        return s;
      }
    }
    /**
     * <code>string tx_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTxIdBytes() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object eventName_;
    /**
     * <code>string event_name = 3;</code>
     */
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      }
    }
    /**
     * <code>string event_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 4;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChaincodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chaincodeId_);
      }
      if (!getTxIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, txId_);
      }
      if (!getEventNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, eventName_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(4, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChaincodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chaincodeId_);
      }
      if (!getTxIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, txId_);
      }
      if (!getEventNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, eventName_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent)) {
        return super.equals(obj);
      }
      org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent other = (org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent) obj;

      if (!getChaincodeId()
          .equals(other.getChaincodeId())) return false;
      if (!getTxId()
          .equals(other.getTxId())) return false;
      if (!getEventName()
          .equals(other.getEventName())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAINCODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChaincodeId().hashCode();
      hash = (37 * hash) + TX_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTxId().hashCode();
      hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getEventName().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *ChaincodeEvent is used for events and registrations that are specific to chaincode
     *string type - "chaincode"
     * </pre>
     *
     * Protobuf type {@code protos.ChaincodeEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.ChaincodeEvent)
        org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.internal_static_protos_ChaincodeEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.internal_static_protos_ChaincodeEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent.class, org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent.Builder.class);
      }

      // Construct using org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chaincodeId_ = "";

        txId_ = "";

        eventName_ = "";

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.internal_static_protos_ChaincodeEvent_descriptor;
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent getDefaultInstanceForType() {
        return org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent.getDefaultInstance();
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent build() {
        org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent buildPartial() {
        org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent result = new org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent(this);
        result.chaincodeId_ = chaincodeId_;
        result.txId_ = txId_;
        result.eventName_ = eventName_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent) {
          return mergeFrom((org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent other) {
        if (other == org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent.getDefaultInstance()) return this;
        if (!other.getChaincodeId().isEmpty()) {
          chaincodeId_ = other.chaincodeId_;
          onChanged();
        }
        if (!other.getTxId().isEmpty()) {
          txId_ = other.txId_;
          onChanged();
        }
        if (!other.getEventName().isEmpty()) {
          eventName_ = other.eventName_;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object chaincodeId_ = "";
      /**
       * <code>string chaincode_id = 1;</code>
       */
      public java.lang.String getChaincodeId() {
        java.lang.Object ref = chaincodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chaincodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chaincode_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getChaincodeIdBytes() {
        java.lang.Object ref = chaincodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chaincodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chaincode_id = 1;</code>
       */
      public Builder setChaincodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chaincodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chaincode_id = 1;</code>
       */
      public Builder clearChaincodeId() {
        
        chaincodeId_ = getDefaultInstance().getChaincodeId();
        onChanged();
        return this;
      }
      /**
       * <code>string chaincode_id = 1;</code>
       */
      public Builder setChaincodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chaincodeId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object txId_ = "";
      /**
       * <code>string tx_id = 2;</code>
       */
      public java.lang.String getTxId() {
        java.lang.Object ref = txId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTxIdBytes() {
        java.lang.Object ref = txId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx_id = 2;</code>
       */
      public Builder setTxId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tx_id = 2;</code>
       */
      public Builder clearTxId() {
        
        txId_ = getDefaultInstance().getTxId();
        onChanged();
        return this;
      }
      /**
       * <code>string tx_id = 2;</code>
       */
      public Builder setTxIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventName_ = "";
      /**
       * <code>string event_name = 3;</code>
       */
      public java.lang.String getEventName() {
        java.lang.Object ref = eventName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEventNameBytes() {
        java.lang.Object ref = eventName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public Builder setEventName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public Builder clearEventName() {
        
        eventName_ = getDefaultInstance().getEventName();
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public Builder setEventNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 4;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.ChaincodeEvent)
    }

    // @@protoc_insertion_point(class_scope:protos.ChaincodeEvent)
    private static final org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent();
    }

    public static org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChaincodeEvent>
        PARSER = new com.google.protobuf.AbstractParser<ChaincodeEvent>() {
      @java.lang.Override
      public ChaincodeEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChaincodeEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChaincodeEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChaincodeEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.hyperledger.fabric.protos.peer.ChaincodeEventPackage.ChaincodeEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ChaincodeEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ChaincodeEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032peer/chaincode_event.proto\022\006protos\"Z\n\016" +
      "ChaincodeEvent\022\024\n\014chaincode_id\030\001 \001(\t\022\r\n\005" +
      "tx_id\030\002 \001(\t\022\022\n\nevent_name\030\003 \001(\t\022\017\n\007paylo" +
      "ad\030\004 \001(\014Bi\n\"org.hyperledger.fabric.proto" +
      "s.peerB\025ChaincodeEventPackageZ,github.co" +
      "m/hyperledger/fabric-protos-go/peerb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_ChaincodeEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_ChaincodeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ChaincodeEvent_descriptor,
        new java.lang.String[] { "ChaincodeId", "TxId", "EventName", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
